#!/bin/sh
{% if dhcp == True %}
ip addr add {{ip}} dev {{network}}
ip link set {{network}} up
{% else %}
dhclient {{network}} &> /dev/null &
while [ $(ip addr show {{network}} | grep -i 'inet' | sed -n 's/.*inet \(.*\)\/.*/\1/p') == '' ]
do
  sleep 1
done
{% endif %}
