#!/bin/sh
ip addr add {{ tinc['network'][network][nodetype][grains['id']]['public-ip'] + "/" + tinc['network'][network][nodetype][grains['id']]['subnet'].split('/')[1] + " " }} dev $INTERFACE
ip link set $INTERFACE up
